<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Primary installation package for Mammoth.LiteMapper.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mammoth.LiteMapper.Abstractions\Mammoth.LiteMapper.Abstractions.csproj" />
    <ProjectReference Include="..\Mammoth.LiteMapper.Generator\Mammoth.LiteMapper.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <None Include="..\Mammoth.LiteMapper.Generator\bin\$(Configuration)\netstandard2.0\Mammoth.LiteMapper.Generator.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>
</Project>
