// <auto-generated/>
#nullable enable
static partial class Mapper
{
    public static partial Target ToTarget(Source source)
    {
        var target = new Target()
        {
            Age = source.Age,
            Name = source.Name
        };
        return target;
    }
}
