// <auto-generated/>
#nullable enable
static partial class Mapper
{
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Target ToTarget(Source source)
    {
        var target = new Target()
        {
            Age = source.Age,
            Name = source.Name
        };
        return target;
    }
}
