// <auto-generated/>
#nullable enable
static partial class Mapper
{
    public static partial void Apply(Source source, Target target)
    {
        if (target == null)
        {
            throw new global::System.ArgumentNullException(nameof(target));
        }
        target.Id = source.Id;
        target.Name = source.Name;
    }
    public static partial Target ApplyReturn(Source source, Target target)
    {
        if (target == null)
        {
            throw new global::System.ArgumentNullException(nameof(target));
        }
        target.Id = source.Id;
        target.Name = source.Name;
        return target;
    }
}
