// <auto-generated/>
#nullable enable
static partial class Mapper
{
    public static partial TargetColor ToTarget(SourceColor source)
    {
        return source switch
            {
                SourceColor.None => TargetColor.None,
                SourceColor.Red => TargetColor.Red,
                SourceColor.Blue => TargetColor.Blue,
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(source), source, "Unmapped enum value.")
            };
    }
}
