// <auto-generated/>
#nullable enable
static partial class Mapper
{
    public static partial Target ToTarget(Source source)
    {
        var target = new Target()
        {
            Country = source.Address.Country.Code,
            Id = source.Identifier
        };
        return target;
    }
}
