using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Mammoth.LiteMapper.Generator.Tests
{
    [TestClass]
    public sealed class Milestone3GeneratorDeclarationTests
    {
        [TestMethod]
        public void GeneratorImplementsIncrementalGeneratorOnly()
        {
            var generatorType = typeof(Mammoth.LiteMapper.Generator.LiteMapperGenerator);

            Assert.IsTrue(typeof(IIncrementalGenerator).IsAssignableFrom(generatorType));
            Assert.IsFalse(typeof(ISourceGenerator).IsAssignableFrom(generatorType));
            Assert.AreEqual(0, generatorType.GetFields(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic).Length);
        }

        [TestMethod]
        public void ValidStaticAndInstanceMappersProduceDeterministicDeclarationSources()
        {
            var result = RunGenerator(@"
using Mammoth.LiteMapper;

[LiteMapper]
public static partial class StaticMapper
{
    public static partial Target ToTarget(Source source);
}

[LiteMapper]
internal sealed partial class InstanceMapper
{
    internal partial Target ToTarget(Source source);
}

public sealed class Source { }
public sealed class Target { }
");

            AssertNoLiteMapperDiagnostics(result);
            Assert.AreEqual(2, result.GeneratedTrees.Length);
            CollectionAssert.AreEqual(
                result.GeneratedTrees.Select(t => t.FilePath).OrderBy(static p => p, StringComparer.Ordinal).ToArray(),
                result.GeneratedTrees.Select(t => t.FilePath).ToArray());
            StringAssert.Contains(result.GeneratedTrees[0].GetText().ToString(), "// <auto-generated/>");
            StringAssert.Contains(result.GeneratedTrees[0].GetText().ToString(), "partial class InstanceMapper");
            StringAssert.Contains(result.GeneratedTrees[1].GetText().ToString(), "partial static class StaticMapper");
        }

        [TestMethod]
        public void InvalidDeclarationsReportStableDiagnostics()
        {
            AssertDiagnostic("LITEMAPPER0001", "[LiteMapper] public class Mapper { }");
            AssertDiagnostic("LITEMAPPER0002", "[LiteMapper] public partial struct Mapper { }");
            AssertDiagnostic("LITEMAPPER0003", "[LiteMapper] public partial class Mapper<T> { }");
            AssertDiagnostic("LITEMAPPER0004", "[LiteMapper] public abstract partial class Mapper { }");
            AssertDiagnostic("LITEMAPPER0001", "public class Outer { [LiteMapper] public partial class Mapper { } }");
        }

        [TestMethod]
        public void InvalidMappingMethodsReportDeclarationDiagnostics()
        {
            AssertDiagnostic("LITEMAPPER0005", "[LiteMapper] public static partial class Mapper { public static partial void Map(Source source); } public sealed class Source { }");
            AssertDiagnostic("LITEMAPPER0006", "[LiteMapper] public static partial class Mapper { public static async partial Target Map(Source source); } public sealed class Source { } public sealed class Target { }");
            AssertDiagnostic("LITEMAPPER0007", "[LiteMapper] public static partial class Mapper { protected static partial Target Map(Source source); } public sealed class Source { } public sealed class Target { }");
            AssertDiagnostic("LITEMAPPER0005", "[LiteMapper] public static partial class Mapper { public static partial Target Map<T>(Source source); } public sealed class Source { } public sealed class Target { }");
            AssertDiagnostic("LITEMAPPER0005", "[LiteMapper] public static partial class Mapper { public static partial Target Map(ref Source source); } public sealed class Source { } public sealed class Target { }");
        }

        [TestMethod]
        public void ConfigurationDiagnosticsAreReported()
        {
            AssertDiagnostic("LITEMAPPER0013", "[LiteMapper][LiteMapper] public static partial class Mapper { }");
            AssertDiagnostic("LITEMAPPER0008", "[LiteMapper(NameMatching = (NameMatching)999)] public static partial class Mapper { }");
            AssertDiagnostic("LITEMAPPER0009", "[LiteMapper] public static partial class Mapper { [MappingOptions(NameMatching = (NameMatching)999)] public static partial Target Map(Source source); } public sealed class Source { } public sealed class Target { }");
            AssertDiagnostic("LITEMAPPER0010", "[assembly: UseMapper(typeof(EmptyExternalMapper))] public static class EmptyExternalMapper { }");
            AssertDiagnostic("LITEMAPPER0011", "public sealed class ExternalMapper { public static Target Map(Source source) => new Target(); } [UseMapper(typeof(ExternalMapper))][LiteMapper] public static partial class Mapper { } public sealed class Source { } public sealed class Target { }");
        }

        [TestMethod]
        public void UnsupportedLanguageVersionIsRejected()
        {
            var result = RunGenerator("[LiteMapper] public static partial class Mapper { }", LanguageVersion.CSharp8);

            AssertDiagnostic(result, "LITEMAPPER0012");
        }

        [TestMethod]
        public void IncrementalGeneratorCachesUnchangedInputsAndInvalidatesChangedMapper()
        {
            var first = CreateDriver().RunGenerators(CreateCompilation("using Mammoth.LiteMapper; [LiteMapper] public static partial class A { } [LiteMapper] public static partial class B { }"));
            var second = first.RunGenerators(CreateCompilation("using Mammoth.LiteMapper; [LiteMapper] public static partial class A { } [LiteMapper] public static partial class B { }"));
            var third = second.RunGenerators(CreateCompilation("using Mammoth.LiteMapper; [LiteMapper] public static partial class A { public static partial Target Map(Source source); } [LiteMapper] public static partial class B { } public sealed class Source { } public sealed class Target { }"));

            CollectionAssert.AreEqual(
                first.GetRunResult().GeneratedTrees.Select(static t => t.GetText().ToString()).ToArray(),
                second.GetRunResult().GeneratedTrees.Select(static t => t.GetText().ToString()).ToArray());

            var secondResult = second.GetRunResult().Results.Single();
            var secondReasons = secondResult.TrackedOutputSteps.Values.SelectMany(static steps => steps).SelectMany(static step => step.Outputs).Select(static output => output.Reason).ToArray();
            Assert.IsTrue(secondReasons.Any(static reason => reason == IncrementalStepRunReason.Cached), "Expected at least one cached incremental output. Actual: " + string.Join(", ", secondReasons.Select(static reason => reason.ToString()).Distinct()));

            var thirdResult = third.GetRunResult().Results.Single();
            var thirdHints = thirdResult.GeneratedSources.Select(static s => s.HintName).ToArray();
            Assert.IsTrue(thirdHints.Any(static h => h.Contains("A.")));
            Assert.IsTrue(thirdHints.Any(static h => h.Contains("B.")));
            var thirdReasons = thirdResult.TrackedOutputSteps.Values.SelectMany(static steps => steps).SelectMany(static step => step.Outputs).Select(static output => output.Reason).ToArray();
            Assert.IsTrue(thirdReasons.Any(static reason => reason != IncrementalStepRunReason.Cached), "Expected at least one changed incremental output. Actual: " + string.Join(", ", thirdReasons.Select(static reason => reason.ToString()).Distinct()));
        }

        private static void AssertDiagnostic(string id, string source)
        {
            AssertDiagnostic(RunGenerator("using Mammoth.LiteMapper;\n" + source), id);
        }

        private static void AssertDiagnostic(GeneratorDriverRunResult result, string id)
        {
            Assert.IsTrue(result.Diagnostics.Any(d => d.Id == id), "Expected " + id + " but found " + string.Join(", ", result.Diagnostics.Select(d => d.Id)));
        }

        private static void AssertNoLiteMapperDiagnostics(GeneratorDriverRunResult result)
        {
            var diagnostics = result.Diagnostics.Where(static d => d.Id.StartsWith("LITEMAPPER", StringComparison.Ordinal)).ToArray();
            Assert.AreEqual(0, diagnostics.Length, string.Join(Environment.NewLine, diagnostics.Select(static d => d.ToString())));
        }

        private static GeneratorDriverRunResult RunGenerator(string source, LanguageVersion languageVersion = LanguageVersion.CSharp9)
        {
            return CreateDriver(languageVersion).RunGenerators(CreateCompilation(source, languageVersion)).GetRunResult();
        }

        private static GeneratorDriver CreateDriver(LanguageVersion languageVersion = LanguageVersion.CSharp9)
        {
            return CSharpGeneratorDriver.Create(
                new[] { new Mammoth.LiteMapper.Generator.LiteMapperGenerator().AsSourceGenerator() },
                parseOptions: CSharpParseOptions.Default.WithLanguageVersion(languageVersion),
                optionsProvider: new TestAnalyzerConfigOptionsProvider(),
                driverOptions: new GeneratorDriverOptions(IncrementalGeneratorOutputKind.None, trackIncrementalGeneratorSteps: true));
        }

        private static Compilation CreateCompilation(string source, LanguageVersion languageVersion = LanguageVersion.CSharp9)
        {
            return CSharpCompilation.Create(
                "Tests",
                new[] { CSharpSyntaxTree.ParseText(source, CSharpParseOptions.Default.WithLanguageVersion(languageVersion)) },
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(System.Runtime.GCSettings).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Mammoth.LiteMapper.LiteMapperAttribute).Assembly.Location),
                },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }

        private sealed class TestAnalyzerConfigOptionsProvider : AnalyzerConfigOptionsProvider
        {
            private static readonly AnalyzerConfigOptions Empty = new TestAnalyzerConfigOptions();

            public override AnalyzerConfigOptions GlobalOptions => Empty;

            public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => Empty;

            public override AnalyzerConfigOptions GetOptions(AdditionalText textFile) => Empty;
        }

        private sealed class TestAnalyzerConfigOptions : AnalyzerConfigOptions
        {
            public override bool TryGetValue(string key, out string value)
            {
                value = string.Empty;
                return false;
            }
        }
    }
}
