<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Mammoth.LiteMapper\Mammoth.LiteMapper.csproj"
                      GlobalPropertiesToRemove="PublishTrimmed;PublishAot" />
    <ProjectReference Include="..\..\src\Mammoth.LiteMapper.Generator\Mammoth.LiteMapper.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all"
                      GlobalPropertiesToRemove="PublishTrimmed;PublishAot" />
  </ItemGroup>
</Project>
